routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('books','BooksController');
Route::resource('borrowers','BorrowerControllerr');
Route::resource('register','register');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/register', 'register@index')->name('register');

Route::get('/admin', 'HomeController@admin')->name('admin');

app/Borrower.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Borrower extends Model
{
   public function books() 
	{ 
		return $this->hasMany('App\books'); 
	}
	
		use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at']; //
}

resources/views/borrowers/create.blade.php
<div class ="container" >
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
            <a class="navbar-brand" href="#">ALWIN SPORTS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
               
                  <a class="nav-link" href="{{ route('books.index')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ route('borrowers.index')}}">Product <span class="sr-only">(current)</span></a>
                      </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('books.index')}}">Brand <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{{ route('books.index')}}">Category <span class="sr-only">(current)</span></a>
                  </li>
				 </nav>

        </div>
</div>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index Page</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
  </head>
  <body>
    <div class="container">
      <h2>Add New Borrowers</h2>
      <br/>
      <form method="post" action="{{url('borrowers')}}" enctype="multipart/form-data">
        @csrf
        <div class="row">
           <div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
             <label for="Name">Name :</label>
             <input type="text" class="form-control" name="name" placeholder="e.g. Alwin">
           </div>
         </div>
		 <div class="row">
           <div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
             <label for="icnumber">IC Number :</label>
             <input type="text" class="form-control" name="icnumber" placeholder="e.g. 951130106131">
           </div>
         </div>
		 <div class="row">
           <div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
             <label for="address">Address :</label>
             <input type="text" class="form-control" name="address" placeholder="e.g. Klang">
           </div>
         </div>
		 <div class="row">
           <div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
             <label for="phonenumber">Phone Number:</label>
             <input type="integer" class="form-control" name="phonenumber" placeholder="e.g. 0163132415">
           </div>
         </div>
		 <div class="row">
           <div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
        
           <div class="form-group col-md-4" style="margin-top:60px">
             <button type="submit" class="btn btn-success">Submit
             </button>
           </div>
         </div>
       </form>
     </div>
    <body>
	

resources/views/borrowers/edit.blade.php
<div class ="container" >
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
            <a class="navbar-brand" href="#">PERPUSTAKAAN DESA</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
               
                  <a class="nav-link" href="{{ route('books.index')}}">Books <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ route('borrowers.index')}}">Borrowers <span class="sr-only">(current)</span></a>
                      </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('books.index')}}">Brand <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{{ route('books.index')}}">Category <span class="sr-only">(current)</span></a>
                  </li>
				 </nav>

        </div>
</div>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Page</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
  <body>
    <div class="container">
      <h2>Edit Borrowers Information</h2>
      <br />
      <form method="post" action="{{action('BorrowerControllerr@update', $borrowers->id)}}">
        @csrf
        <input name="_method" type="hidden" value="PATCH">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name" value="{{$borrowers->name}}">
          </div>
        </div>
		<div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
            <label for="icnumber">IC Number:</label>
            <input type="text" class="form-control" name="icnumber" value="{{$borrowers->icnumber}}">
          </div>
        </div>
		<div class="row">
		<div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
             <label for="address">Address</label>
             <input type="text" class="form-control" name="address" value="{{$borrowers->address}}">
           </div>
         </div>
		 <div class="row">
           <div class="col-md-4">
           </div>
           <div class="form-group col-md-4">
             <label for="phonenumber">Phone Number</label>
             <input type="text" class="form-control" name="phonenumber" value="{{$borrowers->phonenumber}}">
           </div>
         </div>
		 <div class="row">
           <div class="col-md-4">
           </div>
          <div class="form-group col-md-4" style="margin-top:60px">
            <button type="submit" class="btn btn-success" style="margin-left:38px">Update</button>
          </div>
        </div>
          
      </form>
    </div>
  </body>
</html>

resources/views/borrowers/index.blade.php
<div class ="container" >
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      
            <a class="navbar-brand" href="#">Perpustakaan Desa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
               
                  <a class="nav-link" href="{{ route('books.index')}}">Books <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ route('borrowers.index')}}">Borrowers <span class="sr-only">(current)</span></a>
                      </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('books.index')}}">Brand <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{{ route('books.index')}}">Category <span class="sr-only">(current)</span></a>
                  </li>
				 </nav>

        </div>
</div>
 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Borrower Page</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
  </head>
  <body>
    <div class="container">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>No</th>
        <th>Name</th>
        <th>IC Number</th>
		<th>Address</th>
        <th>Phone Number</th>
		
		
        <th colspan=3>Action</th>
      </tr>
    </thead>
<a href="{{ route('borrowers.create')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add  Borrower</a>
    @php
      $i=1;
    @endphp
    @foreach($borrowers as $borrowers)
      <tr>
        <td>@php echo $i++; @endphp</td>
		<td>{{$borrowers->name}}</td>
        <td>{{$borrowers->icnumber}}</td>
        <td>{{$borrowers->address}}</td>
		<td>{{$borrowers->phonenumber}}</td>
        <td><a href="{{action('BorrowerControllerr@edit', $borrowers->id)}}" class="btn btn-warning">Edit</a></td>&nbsp;
          <form action="{{action('BorrowerControllerr@destroy', $borrowers->id)}}" method="post">
            @csrf
            <input name="_method" type="hidden" value="DELETE">
            <td><button class="btn btn-danger" type="submit" onclick="return confirm('Are you sure?')">Delete</button></td>
            @endforeach
          </form>
        </td>
      </td>
    </tr>
  </table>

  </body>
</html>